site_name: Veracode Opensource
site_description: 'Veracode Opensource'
site_author: 'Veracode'
docs_dir: docs/
repo_name: 'Veracode-Community-Projects'
repo_url: 'https://github.com/veracode/Veracode-Community-Projects/'
theme:
  name: 'material'
  features:
    - navigation.instant
  logo: assets/images/favicon.ico
  favicon: assets/images/favicon.ico
nav:
    - Home: index.md
    - Offical Opensource Projects:
        - CI/CD:
            - GitHub: official/ci-cd/github.md
    - Veracode Community Projects:
        - Veracode Delete Sandbox: community/platform-scripts/veracode-delete-sandbox.md
extra_css:
    - css/extra.css