site_name: Veracode Community Projects
site_description: 'A docs test'
site_author: 'test'
docs_dir: docs/
repo_name: 'test'
repo_url: 'https://github.com/mhausenblas/actions-sandbox'
theme:
  name: 'readthedocs'
nav:
    - Home: index.md
    - Offical OSS Projects:
        - Project 1: official/proj1.md
        - Project 2: official/proj1.md
    - Veracode Community Projects:
        - Project 3: official/proj1.md
        - Project 4: official/proj1.md