site_name: Veracode Open Source
site_description: 'Veracode Open Source'
site_author: 'Veracode'
docs_dir: docs/
repo_name: 'Veracode-Community-Projects'
repo_url: 'https://github.com/veracode/Veracode-Community-Projects/'
theme:
  name: 'material'
  features:
    - navigation.instant
  logo: assets/images/favicon.ico
  favicon: assets/images/favicon.ico
nav:
    - Home: index.md
    - Offical Opensource Projects:
        - CI/CD:
            - GitHub: official/ci-cd/github.md
    - Veracode Community Projects:
         - SDK:
            - API Wrapper Libraries: community/sdk/api-wrappers.md
            - CLI Tools: community/sdk/cli.md
            - HMAC Signing Libraries: community/sdk/hmac-signing-libraries.md
         - CI/CD:
            - GitHub: community/ci-cd/github.md
            - GitHub: community/ci-cd/gitlab.md
            - GitHub: community/ci-cd/azuredevops.md
            - GitHub: community/ci-cd/jenkins.md
            - GitHub: community/ci-cd/docker.md
            - GitHub: community/ci-cd/bamboo.md
            - GitHub: community/ci-cd/circle-ci.md
            - GitHub: community/ci-cd/concourse-ci.md
            - GitHub: community/ci-cd/travis.md
        - IDE:
            - VsCode: community/ide/vscode.md
        - Testing Tools:
            - Postman: community/sdk/postman.md
            - Insomnia: community/sdk/insomnia.md
        - Utility:
            - VsCode: community/utility/administration.md
            - VsCode: community/utility/investigation.md
        - Workflow:
            - VsCode: community/workflow/notifications.md
        - Resources:
            - Insecure Applications: community/resources/insecure-applications.md
            - Secure Coding Examples: community/resources/secure-coding-samples.md

extra_css:
    - css/extra.css
    - css/font-awesome.min.css
extra_javascript:
    - js/extra.js